language: python

python:
    - "2.7.13"
    - "3.6"

install:
    - pip install tox-travis ipython ptpython bpython
    - pip install setuptools==34.3.1

script: tox

notifications:
  email:
    on_success: never
    on_failure: always
